AllCops:
  Include:
    - '**/Gemfile'
    - '**/config.ru'
    - '**/Rakefile'
    - '**/*.rake'
    - '**/*.gemfile'
    - '**/*.gemspec'
  Exclude:
    - 'lib/sequel-rails.rb'

HashSyntax:
  EnforcedStyle: hash_rockets

inherit_from: rubocop-todo.yml
