language: ruby
rvm:
  - 1.9.3
env:
  - "TEST_ADAPTER=postgresql TEST_OWNER=postgres TEST_USERNAME=postgres"
  - "TEST_ADAPTER=mysql TEST_USERNAME=root TEST_ENCODING=utf8"
  - "TEST_ADAPTER=mysql2 TEST_USERNAME=root TEST_ENCODING=utf8"
  - "TEST_ADAPTER=sqlite3 TEST_DATABASE=':memory:'"
