language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - jruby-9.1.16.0
before_script:
  - mysql -e 'create database sequel_rails_test;'
  - mysql -e 'create database sequel_rails_test_mysql2;'
  - mysql -e 'create database sequel_rails_test_storage_dev;'
  - psql  -c 'create database sequel_rails_test_storage_dev;' -U postgres
  - psql  -c 'create database sequel_rails_test;' -U postgres
env:
  - SEQUEL='~> 4.0'
  - SEQUEL='~> 5.0'
gemfile:
  - ci/rails-4.0.gemfile
  - ci/rails-4.1.gemfile
  - ci/rails-4.2.gemfile
  - ci/rails-5.0.gemfile
  - ci/rails-5.1.gemfile
matrix:
  exclude:
    - rvm: 2.4.2
      gemfile: ci/rails-4.0.gemfile
    - rvm: 2.4.2
      gemfile: ci/rails-4.1.gemfile
    - rvm: 2.5.0
      gemfile: ci/rails-4.0.gemfile
    - rvm: 2.5.0
      gemfile: ci/rails-4.1.gemfile
notifications:
  email:
    - jonathan.tron@metrilio.com
