language: ruby
cache: bundler
sudo: false
jdk: oraclejdk8
rvm:
  - ree
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - jruby-18mode
  - jruby-19mode
  - jruby-9.0.5.0
  - jruby-9.1.2.0
before_script:
  - mysql -e 'create database sequel_rails_test;'
  - mysql -e 'create database sequel_rails_test_mysql2;'
  - psql -c 'create database sequel_rails_test;' -U postgres
env:
  - SEQUEL='~> 3.0'
  - SEQUEL='~> 4.0'
gemfile:
  - ci/rails-3.2.gemfile
  - ci/rails-4.0.gemfile
  - ci/rails-4.1.gemfile
  - ci/rails-4.2.gemfile
  - ci/rails-5.0.gemfile
matrix:
  exclude:
    - rvm: 2.2.4
      gemfile: ci/rails-3.2.gemfile
    - rvm: 2.3.0
      gemfile: ci/rails-3.2.gemfile
    - rvm: jruby-9.0.5.0
      gemfile: ci/rails-3.2.gemfile
    - rvm: jruby-9.1.2.0
      gemfile: ci/rails-3.2.gemfile
    - rvm: ree
      gemfile: ci/rails-4.0.gemfile
    - rvm: 1.8.7
      gemfile: ci/rails-4.0.gemfile
    - rvm: jruby-18mode
      gemfile: ci/rails-4.0.gemfile
    - rvm: ree
      gemfile: ci/rails-4.1.gemfile
    - rvm: 1.8.7
      gemfile: ci/rails-4.1.gemfile
    - rvm: jruby-18mode
      gemfile: ci/rails-4.1.gemfile
    - rvm: ree
      gemfile: ci/rails-4.2.gemfile
    - rvm: 1.8.7
      gemfile: ci/rails-4.2.gemfile
    - rvm: jruby-18mode
      gemfile: ci/rails-4.2.gemfile
    - rvm: ree
      gemfile: ci/rails-5.0.gemfile
    - rvm: 1.8.7
      gemfile: ci/rails-5.0.gemfile
    - rvm: jruby-18mode
      gemfile: ci/rails-5.0.gemfile
    - rvm: jruby-19mode
      gemfile: ci/rails-5.0.gemfile
    - rvm: 1.9.3
      gemfile: ci/rails-5.0.gemfile
    - rvm: 2.0.0
      gemfile: ci/rails-5.0.gemfile
    - rvm: 2.1.10
      gemfile: ci/rails-5.0.gemfile
    - gemfile: ci/rails-3.2.gemfile
      env: SEQUEL='~> 4.0'
notifications:
  email:
    - jonathan.tron@metrilio.com
