language: ruby
cache: bundler
services:
  - mysql
  - postgresql
rvm:
  - 2.2.9
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - jruby-9.2.8.0
before_script:
  - mysql -e 'create database sequel_rails_test;'
  - mysql -e 'create database sequel_rails_test_mysql2;'
  - mysql -e 'create database sequel_rails_test_storage_dev;'
  - psql  -c 'create database sequel_rails_test_storage_dev;' -U postgres
  - psql  -c 'create database sequel_rails_test;' -U postgres
env:
  - SEQUEL='~> 4.0'
  - SEQUEL='~> 5.0'
gemfile:
  - ci/rails-4.0.gemfile
  - ci/rails-4.1.gemfile
  - ci/rails-4.2.gemfile
  - ci/rails-5.0.gemfile
  - ci/rails-5.1.gemfile
  - ci/rails-5.2.gemfile
  - ci/rails-6.0.gemfile
matrix:
  exclude:
    - rvm: 2.4.9
      gemfile: ci/rails-4.0.gemfile
    - rvm: 2.4.9
      gemfile: ci/rails-4.1.gemfile
    - rvm: 2.5.7
      gemfile: ci/rails-4.0.gemfile
    - rvm: 2.5.7
      gemfile: ci/rails-4.1.gemfile
    - rvm: 2.6.5
      gemfile: ci/rails-4.0.gemfile
    - rvm: 2.6.5
      gemfile: ci/rails-4.1.gemfile
    - rvm: 2.6.5
      gemfile: ci/rails-4.2.gemfile
    - rvm: 2.6.5
      gemfile: ci/rails-5.0.gemfile
    - rvm: 2.6.5
      gemfile: ci/rails-5.1.gemfile
    - rvm: jruby-9.2.8.0
      gemfile: ci/rails-4.0.gemfile
    - rvm: jruby-9.2.8.0
      gemfile: ci/rails-4.1.gemfile
    - rvm: 2.2.9
      gemfile: ci/rails-5.2.gemfile
    - rvm: 2.2.9
      gemfile: ci/rails-6.0.gemfile
    - rvm: 2.3.8
      gemfile: ci/rails-6.0.gemfile
    - rvm: 2.4.9
      gemfile: ci/rails-6.0.gemfile

notifications:
  email:
    - jonathan.tron@metrilio.com
