language: ruby
rvm:
  - ree
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
  - jruby-18mode
  - jruby-19mode
env:
  - SEQUEL='~> 3.0'
  - SEQUEL='~> 4.0'
gemfile:
  - ci/rails-3.2.gemfile
  - ci/rails-4.0.gemfile
  - ci/rails-4.1.gemfile
  - ci/rails-4.2.gemfile
matrix:
  exclude:
    - rvm: ree
      gemfile: ci/rails-4.0.gemfile
      env: SEQUEL='~> 3.0'
    - rvm: ree
      gemfile: ci/rails-4.0.gemfile
      env: SEQUEL='~> 4.0'
    - rvm: 1.8.7
      gemfile: ci/rails-4.0.gemfile
      env: SEQUEL='~> 3.0'
    - rvm: 1.8.7
      gemfile: ci/rails-4.0.gemfile
      env: SEQUEL='~> 4.0'
    - rvm: jruby-18mode
      gemfile: ci/rails-4.0.gemfile
      env: SEQUEL='~> 3.0'
    - rvm: jruby-18mode
      gemfile: ci/rails-4.0.gemfile
      env: SEQUEL='~> 4.0'
    - rvm: ree
      gemfile: ci/rails-4.1.gemfile
      env: SEQUEL='~> 3.0'
    - rvm: ree
      gemfile: ci/rails-4.1.gemfile
      env: SEQUEL='~> 4.0'
    - rvm: 1.8.7
      gemfile: ci/rails-4.1.gemfile
      env: SEQUEL='~> 3.0'
    - rvm: 1.8.7
      gemfile: ci/rails-4.1.gemfile
      env: SEQUEL='~> 4.0'
    - rvm: jruby-18mode
      gemfile: ci/rails-4.1.gemfile
      env: SEQUEL='~> 3.0'
    - rvm: jruby-18mode
      gemfile: ci/rails-4.1.gemfile
      env: SEQUEL='~> 4.0'
    - rvm: ree
      gemfile: ci/rails-4.2.gemfile
      env: SEQUEL='~> 3.0'
    - rvm: ree
      gemfile: ci/rails-4.2.gemfile
      env: SEQUEL='~> 4.0'
    - rvm: 1.8.7
      gemfile: ci/rails-4.2.gemfile
      env: SEQUEL='~> 3.0'
    - rvm: 1.8.7
      gemfile: ci/rails-4.2.gemfile
      env: SEQUEL='~> 4.0'
    - rvm: jruby-18mode
      gemfile: ci/rails-4.2.gemfile
      env: SEQUEL='~> 3.0'
    - rvm: jruby-18mode
      gemfile: ci/rails-4.2.gemfile
      env: SEQUEL='~> 4.0'
notifications:
  email:
    - jonathan.tron@metrilio.com
